disabled_rules: # rule identifiers to exclude from running
  - trailing_newline
  - type_name
  - function_body_length
  - missing_docs
  - cyclomatic_complexity
  - type_body_length
  - function_parameter_count
  - file_length
  - unused_closure_parameter
  - empty_parentheses_with_trailing_closure
  - redundant_string_enum_value
  - large_tuple
  - class_delegate_protocol
  - syntactic_sugar
  - implicit_getter
  - weak_delegate
  - shorthand_operator
  - trailing_comma
  - unused_optional_binding
  - private_over_fileprivate
  - empty_enum_arguments
  - discarded_notification_center_observer
  - block_based_kvo
  - nesting
  - is_disjoint
  - multiple_closures_with_trailing_closure
  - fallthrough
  - switch_case_alignment
  - trailing_whitespace
  - leading_whitespace
  - operator_whitespace
  - legacy_cggeometry_functions
  - unneeded_break_in_switch
  - closure_parameter_position

opt_in_rules: # some rules are only opt-in
  - todo
  - mark
  - closing_brace
  - opening_brace
  - return_arrow_whitespace
  - trailing_semicolon
  - statement_position
  - explicit_init
  - shorthand_operator
  - deployment_target
  - discouraged_optional_collection
  - duplicate_imports
  - empty_string
  - overridden_super_call
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_objc_attribute
  - redundant_type_annotation
  - unused_import
  - empty_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - ContentAppTests/
  - ContentAppUITests/
  - generated

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
trailing_semicolon: error
empty_count: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
statement_position: error
colon: error
comma: error
force_try: warning
force_cast: warning

line_length: 1000
