trigger:
- main
pool:
  vmImage: 'macOS-12'

variables:
  - group: git-credentials
  - group: source-clear-credentials
  - group: ios-signing
  - group: content-ios
  - name: configuration
    value: 'Release'
  - name: sdk
    value: 'iphoneos'
  - name: cocoapods_path
    value: $(Pipeline.Workspace)/.cocoapods
  - name: "DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"
    value: "-asc_provider $(appleTeamId)"

steps:
- checkout: self

- task: Cache@2
  inputs:
    key: 'cocoapods | Podfile.lock'
    restoreKeys: cocoapods
    path: $(cocoapods_path)
  displayName: Cache CocoaPods Specs

- task: Cache@2
  inputs:
    key: 'pods | Podfile.lock'
    restoreKeys: pods
    path: Pods
  displayName: Cache Pods

- task: ios-bundle-version@1
  inputs:
    sourcePath: 'ContentApp/Supporting Files/Info.plist'
    versionCodeOption: 'buildid'
    versionCode: '$(build_version)'
    versionName: '1.9.0-M1'
    printFile: true

- task: CmdLine@2
  displayName: Installing pods
  inputs:
    script: |
      pod install || pod install --repo-update
  env:
    CP_HOME_DIR: $(cocoapods_path)

- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true

- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioning_profile)'
   removeProfile: true
- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioning_profile_share)'
   removeProfile: true
- task: DownloadSecureFile@1
  name: prov_profile
  inputs:
    secureFile: '$(provisioning_profile)'
- task: DownloadSecureFile@1
  name: prov_profile_share
  inputs:
    secureFile: '$(provisioning_profile_share)'

- script: |
    sudo xcode-select -s /Applications/Xcode_14.2.app
  displayName: Selects a specific version of Xcode

- task: CmdLine@2
  displayName: 'Build and Pilot'
  inputs:
    script: 'bundle update && bundle exec fastlane build_and_pilot'
  env:
      FASTLANE_DISABLE_COLORS: 'true'
      FASTLANE_USER: $(appstore_upload_user)
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: $(appstore_upload_token)
      PROV_PROFILE: $(prov_profile.secureFilePath)
      PROV_PROFILE_SHARE: $(prov_profile_share.secureFilePath)
      SIGNING_IDENTITY: $(signing_identity)
      APPSTORE_APP_ID: $(appstore_app_id)
      CONFIGURATION: $(configuration)
      FASTLANE_ITC_TEAM_ID: $(appleTeamId)
      FASTLANE_ITC_PP_ID: $(provider_public_id)


- task: CmdLine@2
  inputs:
    script: 'curl -sSL https://download.sourceclear.com/ci.sh | sh'
  displayName: 'Performing Source Clear checks'
  env:
    SRCCLR_API_TOKEN: $(source_clear_token)
