name: Veracode Static Analysis Demo
# TODO - currently only runs manually, when you run this depends on on your workflow
#.       see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows for possibilities
on: 
    push:
        branches:
          - main
    workflow_dispatch:
    
jobs:
  static_analysis:
    name: Static Analysis
    # Monterey or higher is required for gen-ir
    runs-on: macos-12
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Setup
#        env: 
#          NotificationEndpointDebug: ${{ secrets.NotificationEndpointDebug }}
#          NotificationEndpointRelease: ${{ secrets.NotificationEndpointRelease }}
        run: |
            cd /Users/runner/work/alfresco-mobile-workspace-ios-enterprise/alfresco-mobile-workspace-ios-enterprise
            gem install bundler:2.3.11
            bundle install
            bundle exec pod install
      
      - name: Install Homebrew dependencies
        run: brew tap veracode/tap && brew install gen-ir
        
      - name: Export a Build Log with xcodebuild - clean
        run: xcodebuild clean

      # Note that code signing is disabled, for analysis purposes we don't need a signed build.
      - name: Export a Build Log with xcodebuild - archive
        run: |
            xcodebuild archive \
              -workspace ContentApp.xcworkspace \
              -scheme ContentApp \
              -configuration Debug \
              -destination generic/platform=iOS \
              -archivePath ContentApp.xcarchive \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              DEBUG_INFOMATION_FORMAT=dwarf-with-dsym \
              ENABLE_BITCODE=NO > build.log

      - name: Generate IR with a Build Log
        run:  gen-ir build.log ContentApp.xcarchive/IR
        
      - name: Build Veracode dir
        run: |
          mkdir veracode
          zip veracode/ContentApp-Podfile.zip Podfile.lock
          zip -r veracode/ContentApp.xcarchive.zip ContentApp.xcarchive
      # Can't use Veracode GitHub Action because container actions not supported on MacOS runners
      - name: Upload & Scan
        run: |
          wget https://search.maven.org/remotecontent?filepath=com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/22.10.10.4/vosp-api-wrappers-java-22.10.10.4.jar -O VeracodeJavaAPI.jar
          java \
            -jar VeracodeJavaAPI.jar \
            -debug \
            -deleteincompletescan 2 \
            -action uploadandscan \
            -vid ${{ secrets.VERACODE_API_ID }} \
            -vkey ${{ secrets.VERACODE_API_KEY }} \
            -appname "iOS AMW" \
            -createprofile true \
            -criticality VeryHigh \
            -sandboxname iOS_AMW-${{ github.run_number }} \
            -createsandbox true \
            -version "commit:${{ github.sha }},run_id:${{ github.run_id }},attempt_nr:${{ github.run_attempt }}" \
            -filepath veracode
